#配置数据源
spring:
  datasource:
    url: jdbc:mysql://123.56.31.115:3306/collect?useUnicode=true&characterEncoding=utf8
    username: lihang
    password: lihang
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: classpath:/templates/
      suffix: .html

#================================================= mybatis-plus start =================================================
mybatis-plus:
  # config-location:
  # classpath:/mapper/*Mapper.xml

  mapper-locations: classpath*:/Users/lihang/Work/WorkSpace/collect/src/main/resources/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.malt.*.entity
  configuration:
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
  global-config:
    # 刷新mapper 调试神器
    refresh: true
    banner: false
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    # 数据库相关配置
    db-config:
      db-type: mysql
      # 主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      # 字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
#================================================= mybatis-plus end ===================================================
server:
  port: 10001
